import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "./components/authcomponents/AuthContext/AuthContext";
import Header from "./components/shared_components/Header/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

        <nav className="sticky z-50 top-0">
          <Header />
        </nav>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
